### ISSUE TITLE
Change or format 

### ISSUE THREAD

**Issue by Lohith-Loke** [stuarthayhurst/argon-icon-theme#3]
hi 
Correct me if i m wrong 
most theme on GitHub have a release file  which consists of  final release 
this doesn't seem to have one 

thank you for u r attention

**Comment by stuarthayhurst** [comment]
As new icons are added, the source files for the icons as well as the .png files for the icons are added to the project. This means a separate release file isn't needed, and the project can be installed `sudo make install` from inside the source files automatically provided when the release is created.

If that helped, feel free to close the issue, unless you have another question. Thanks for the star by the way :)

**Comment by Lohith-Loke** [comment]
thanks for your help 
Appreciate u  r time
